// pull.js - Pull asset map from Reshot platform
// Generates JSON, TypeScript, or CSV files for local workflows
const chalk = require("chalk");
const fs = require("fs-extra");
const path = require("path");
const config = require("../lib/config");
const apiClient = require("../lib/api-client");

/**
 * Convert a string to camelCase for TypeScript keys
 */
function toCamelCase(str) {
  return str
    .toLowerCase()
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, chr) => chr.toUpperCase())
    .replace(/^[A-Z]/, (chr) => chr.toLowerCase());
}

function normalizeHostedAssetUrl(urlString) {
  if (!urlString || typeof urlString !== "string") {
    return urlString;
  }

  let normalized = urlString;
  if (!normalized.includes("?") && normalized.includes("&")) {
    const firstAmp = normalized.indexOf("&");
    normalized = `${normalized.slice(0, firstAmp)}?${normalized.slice(firstAmp + 1)}`;
  }

  const parsed = new URL(normalized);
  const capture = parsed.searchParams.get("capture");
  if (capture && !parsed.searchParams.get("step")) {
    parsed.searchParams.set("step", capture);
  }
  parsed.searchParams.delete("capture");

  return parsed.toString();
}

function normalizeHostedAssetUrlWithMeta(urlString) {
  const normalized = normalizeHostedAssetUrl(urlString);
  return {
    url: normalized,
    repaired: normalized !== urlString,
  };
}

function normalizeAssetEntry(entry) {
  if (!entry || typeof entry !== "object") {
    return { entry, repairs: 0 };
  }

  if (Array.isArray(entry.steps)) {
    return {
      entry: {
        ...entry,
        steps: entry.steps.map((step) => {
          const src = normalizeHostedAssetUrlWithMeta(step.src);
          const poster = step.poster
            ? normalizeHostedAssetUrlWithMeta(step.poster)
            : null;
          return {
            ...step,
            src: src.url,
            poster: poster ? poster.url : step.poster,
          };
        }),
      },
      repairs: entry.steps.reduce((count, step) => {
        const src = normalizeHostedAssetUrlWithMeta(step.src);
        const poster = step.poster
          ? normalizeHostedAssetUrlWithMeta(step.poster)
          : null;
        return count + (src.repaired ? 1 : 0) + (poster?.repaired ? 1 : 0);
      }, 0),
    };
  }

  return {
    entry: {
      ...entry,
      src: entry.src ? normalizeHostedAssetUrl(entry.src) : entry.src,
      poster: entry.poster ? normalizeHostedAssetUrl(entry.poster) : entry.poster,
    },
    repairs:
      (entry.src && normalizeHostedAssetUrlWithMeta(entry.src).repaired ? 1 : 0) +
      (entry.poster && normalizeHostedAssetUrlWithMeta(entry.poster).repaired ? 1 : 0),
  };
}

function normalizeAssetMap(assets) {
  const normalized = {};
  let repairs = 0;

  for (const [group, visuals] of Object.entries(assets || {})) {
    normalized[group] = {};

    for (const [visualKey, variants] of Object.entries(visuals || {})) {
      normalized[group][visualKey] = {};

      for (const [variant, entry] of Object.entries(variants || {})) {
        const normalizedEntry = normalizeAssetEntry(entry);
        normalized[group][visualKey][variant] = normalizedEntry.entry;
        repairs += normalizedEntry.repairs;
      }
    }
  }

  return { assets: normalized, repairs };
}

function validateHostedAssetUrl(urlString) {
  if (!urlString || typeof urlString !== "string") {
    return;
  }

  if (!urlString.includes("?") && (urlString.includes("&step=") || urlString.includes("&poster="))) {
    throw new Error(`Malformed asset URL emitted without query delimiter: ${urlString}`);
  }

  const parsed = new URL(urlString);
  if (parsed.searchParams.has("capture")) {
    throw new Error(`Legacy capture param emitted in normalized output: ${urlString}`);
  }
}

function validateAssetMap(assets) {
  for (const visuals of Object.values(assets || {})) {
    for (const variants of Object.values(visuals || {})) {
      for (const entry of Object.values(variants || {})) {
        if (entry && typeof entry === "object" && Array.isArray(entry.steps)) {
          for (const step of entry.steps) {
            validateHostedAssetUrl(step.src);
            if (step.poster) {
              validateHostedAssetUrl(step.poster);
            }
          }
          continue;
        }

        validateHostedAssetUrl(entry?.src);
        if (entry?.poster) {
          validateHostedAssetUrl(entry.poster);
        }
      }
    }
  }
}

/**
 * Generate TypeScript code from the assets object
 * This provides type safety - if a visual is deleted, the build will fail
 */
function generateTypeScript(assets, includeMetadata = false) {
  const lines = [
    "// GENERATED BY RESHOT - DO NOT EDIT",
    "// Run 'npx reshot pull' to regenerate this file",
    "",
  ];

  if (includeMetadata) {
    // Full export with all metadata (src, width, height, type, alt)
    lines.push("export const ReshotVisuals = {");
    
    for (const [group, visuals] of Object.entries(assets)) {
      lines.push(`  ${group}: {`);
      
      for (const [visualKey, variants] of Object.entries(visuals)) {
        lines.push(`    ${visualKey}: {`);
        
        for (const [variant, asset] of Object.entries(variants)) {
          lines.push(`      ${variant}: {`);
          lines.push(`        type: "${asset.type}",`);
          lines.push(`        alt: "${asset.alt.replace(/"/g, '\\"')}",`);
          if (Array.isArray(asset.steps)) {
            lines.push(`        steps: [`);
            for (const step of asset.steps) {
              lines.push("          {");
              lines.push(`            step: "${step.step}",`);
              lines.push(`            src: "${step.src}",`);
              lines.push(`            type: "${step.type}",`);
              if (step.width) lines.push(`            width: ${step.width},`);
              if (step.height) lines.push(`            height: ${step.height},`);
              if (step.poster) lines.push(`            poster: "${step.poster}",`);
              lines.push("          },");
            }
            lines.push("        ],");
          } else {
            lines.push(`        src: "${asset.src}",`);
            if (asset.width) lines.push(`        width: ${asset.width},`);
            if (asset.height) lines.push(`        height: ${asset.height},`);
            if (asset.poster) lines.push(`        poster: "${asset.poster}",`);
          }
          lines.push(`      },`);
        }
        
        lines.push(`    },`);
      }
      
      lines.push(`  },`);
    }
    
    lines.push("} as const;");
    lines.push("");
    lines.push("export type ReshotVisualKey = keyof typeof ReshotVisuals;");
  } else {
    // Simplified export - just URLs for easy access
    lines.push("export const ReshotVisuals = {");
    
    for (const [group, visuals] of Object.entries(assets)) {
      lines.push(`  ${group}: {`);
      
      for (const [visualKey, variants] of Object.entries(visuals)) {
        // If there's only a default variant, flatten it
        if (Object.keys(variants).length === 1 && variants.default) {
          if (Array.isArray(variants.default.steps)) {
            lines.push(`    ${visualKey}: ${JSON.stringify(variants.default.steps)},`);
          } else {
            lines.push(`    ${visualKey}: "${variants.default.src}",`);
          }
        } else {
          lines.push(`    ${visualKey}: {`);
          for (const [variant, asset] of Object.entries(variants)) {
            if (Array.isArray(asset.steps)) {
              lines.push(`      ${variant}: ${JSON.stringify(asset.steps)},`);
            } else {
              lines.push(`      ${variant}: "${asset.src}",`);
            }
          }
          lines.push(`    },`);
        }
      }
      
      lines.push(`  },`);
    }
    
    lines.push("} as const;");
    lines.push("");
    lines.push("export type ReshotVisualKey = keyof typeof ReshotVisuals;");
  }

  return lines.join("\n");
}

/**
 * Main pull command
 * @param {Object} options - Command options
 * @param {string} options.format - Output format: 'json', 'ts', 'csv'
 * @param {string} options.output - Output file path
 * @param {boolean} options.full - Include full metadata (for ts format)
 * @param {string} options.status - Filter by status: 'approved', 'pending', 'all'
 */
async function pullCommand(options = {}) {
  const {
    format = "json",
    output = null,
    full = false,
    status = "all",
    noExit = false,
  } = options;

  console.log(chalk.blue("⬇ Pulling asset map from Reshot...\n"));

  // Load project configuration
  let projectConfig;
  try {
    projectConfig = config.readConfig();
  } catch (e) {
    console.error(
      chalk.red("Error: No reshot.config.json found. Run 'reshot init' first.")
    );
    if (!noExit) process.exit(1);
    return { success: false, error: "No reshot.config.json found" };
  }

  let projectId =
    process.env.RESHOT_PROJECT_ID ||
    projectConfig._metadata?.projectId ||
    projectConfig.projectId;
  if (!projectId) {
    // Fall back to reading projectId from .reshot/settings.json (written by `reshot auth`)
    try {
      const settings = config.readSettings();
      if (settings?.projectId) {
        projectId = settings.projectId;
      }
    } catch (e) {
      // No settings file either
    }
  }
  if (!projectId) {
      console.error(
        chalk.red("Error: No projectId found. Add it to reshot.config.json or run 'reshot auth' first.")
      );
    if (!noExit) process.exit(1);
    return { success: false, error: "No projectId found" };
  }

  // Check authentication
  let settings;
  try {
    settings = config.readSettings();
  } catch (e) {
    console.error(
      chalk.red("Error: Not authenticated. Run 'reshot auth' first.")
    );
    if (!noExit) process.exit(1);
    return { success: false, error: "Not authenticated" };
  }
  if (!settings?.apiKey) {
    console.error(
      chalk.red("Error: Not authenticated. Run 'reshot auth' first.")
    );
    if (!noExit) process.exit(1);
    return { success: false, error: "Not authenticated" };
  }

  if (settings.projectId && projectId !== settings.projectId) {
    console.warn(
      chalk.yellow(
        `  ⚠ Project ID mismatch: active project is ${projectId}, but authenticated project is ${settings.projectId}.`
      )
    );
    console.warn(
      chalk.yellow(
        `    This will cause auth failures. Run 'reshot setup --force' to re-link.\n`
      )
    );
  }

  try {
    // Fetch the asset map from the API
    console.log(chalk.gray(`  Fetching assets for project: ${projectId}`));
    console.log(chalk.gray(`  Status filter: ${status}`));

    const response = await apiClient.exportVisuals(projectId, {
      format: "json", // Always fetch JSON, we'll transform locally
      status,
    });

    if (!response || !response.assets) {
      console.error(chalk.red("Error: Invalid response from API"));
      if (!noExit) process.exit(1);
      return { success: false, error: "Invalid response from API" };
    }

    const normalization = normalizeAssetMap(response.assets);
    const normalizedAssets = normalization.assets;
    validateAssetMap(normalizedAssets);

    const { meta } = response;
    const assetCount = Object.values(normalizedAssets).reduce(
      (count, group) => count + Object.keys(group).length,
      0
    );

    if (assetCount === 0) {
      console.log(chalk.yellow(`  ⚠ Fetched 0 visuals.\n`));
      console.log(chalk.gray(`  Possible reasons:`));
      if (status === "approved") {
        console.log(chalk.gray(`    • No visuals approved yet. Try: reshot pull --status all`));
      } else if (status === "pending") {
        console.log(chalk.gray(`    • No pending visuals. Try: reshot pull --status all`));
      }
      console.log(chalk.gray(`    • No visuals published. Run: reshot publish`));
      console.log(chalk.gray(`    • Wrong project. Active project: ${projectId}`));
      console.log(chalk.gray(`    • Check: ${settings.platformUrl || "https://reshot.dev"}\n`));
    } else {
      console.log(chalk.green(`  ✓ Fetched ${assetCount} visuals\n`));
    }

    // Determine output path
    let outputPath = output;
    if (!outputPath) {
      // Default paths based on format
      const defaultPaths = {
        json: "src/data/reshot-assets.json",
        ts: "src/data/visuals.ts",
        csv: "reshot-assets.csv",
      };
      outputPath = defaultPaths[format] || "reshot-assets.json";
    }

    // Ensure the output directory exists
    const outputDir = path.dirname(path.resolve(outputPath));
    await fs.ensureDir(outputDir);

    // Generate output based on format
    let content;
    let contentType;

    switch (format) {
      case "ts":
        content = generateTypeScript(normalizedAssets, full);
        contentType = "TypeScript";
        break;

      case "csv":
        // Generate CSV format
        const headers = ["Key", "Group", "Name", "Context", "Type", "Unbreakable_URL", "Width", "Height"];
        const rows = [headers.join(",")];
        
        for (const [group, visuals] of Object.entries(normalizedAssets)) {
          for (const [visualKey, variants] of Object.entries(visuals)) {
            for (const [variant, asset] of Object.entries(variants)) {
              if (Array.isArray(asset.steps)) {
                for (const step of asset.steps) {
                  const type = step.type.split("/")[0];
                  rows.push(
                    [
                      `${group}/${visualKey}/${step.step}`,
                      group,
                      visualKey,
                      variant,
                      type,
                      step.src,
                      step.width || "",
                      step.height || "",
                    ].join(",")
                  );
                }
                continue;
              }

              const type = asset.type.split("/")[0]; // 'image' or 'video'
              rows.push(
                [
                  `${group}/${visualKey}`,
                  group,
                  visualKey,
                  variant,
                  type,
                  asset.src,
                  asset.width || "",
                  asset.height || "",
                ].join(",")
              );
            }
          }
        }
        
        content = rows.join("\n");
        contentType = "CSV";
        break;

      case "json":
      default:
        content = JSON.stringify({ meta, assets: normalizedAssets }, null, 2);
        contentType = "JSON";
        break;
    }

    // Write the output file
    await fs.writeFile(path.resolve(outputPath), content, "utf-8");

    console.log(chalk.green(`✓ Generated ${contentType} file: ${outputPath}`));
    console.log(chalk.gray(`  ${assetCount} visuals exported\n`));

    // Show format-specific usage instructions
    if (format === "ts") {
      console.log(chalk.blue("━━━ TypeScript Usage ━━━\n"));
      console.log(chalk.white("Import in your React/Next.js component:\n"));
      console.log(chalk.cyan('  import { ReshotVisuals } from "./visuals";\n'));
      console.log(chalk.white("Use with full autocomplete support:\n"));
      console.log(chalk.cyan("  // Single context (flattened)"));
      console.log(chalk.cyan("  <img src={ReshotVisuals.dashboard.mainView} />\n"));
      console.log(chalk.cyan("  // Multiple contexts (dark mode, locales)"));
      console.log(chalk.cyan("  <img src={ReshotVisuals.dashboard.mainView.default} />"));
      console.log(chalk.cyan("  <img src={ReshotVisuals.dashboard.mainView.dark} />\n"));
      if (!full) {
        console.log(chalk.gray("  Tip: Use --full flag to include width, height, and alt text\n"));
      }
    } else if (format === "json") {
      console.log(chalk.blue("━━━ JSON Usage ━━━\n"));
      console.log(chalk.white("Import in JavaScript/TypeScript:\n"));
      console.log(chalk.cyan('  import assets from "./reshot-assets.json";\n'));
      console.log(chalk.white("Access assets with dot notation:\n"));
      console.log(chalk.cyan("  <img"));
      console.log(chalk.cyan("    src={assets.assets.dashboard.mainView.default.src}"));
      console.log(chalk.cyan("    width={assets.assets.dashboard.mainView.default.width}"));
      console.log(chalk.cyan("    height={assets.assets.dashboard.mainView.default.height}"));
      console.log(chalk.cyan("    alt={assets.assets.dashboard.mainView.default.alt}"));
      console.log(chalk.cyan("  />\n"));
    } else if (format === "csv") {
      console.log(chalk.blue("━━━ CSV Usage ━━━\n"));
      console.log(chalk.white("Import into your CMS:\n"));
      console.log(chalk.gray("  1. Open Contentful / Webflow / WordPress"));
      console.log(chalk.gray("  2. Navigate to bulk import/media settings"));
      console.log(chalk.gray(`  3. Upload ${outputPath}`));
      console.log(chalk.gray("  4. Map columns to your asset fields\n"));
      console.log(chalk.white("CSV Columns:\n"));
      console.log(chalk.gray("  • Key           - Unique asset identifier"));
      console.log(chalk.gray("  • Group         - Scenario/folder grouping"));
      console.log(chalk.gray("  • Name          - Human-readable name"));
      console.log(chalk.gray("  • Context       - Variant (default, dark, fr-FR)"));
      console.log(chalk.gray("  • Type          - image or video"));
      console.log(chalk.gray("  • Unbreakable_URL - CDN URL (never changes)"));
      console.log(chalk.gray("  • Width/Height  - Dimensions in pixels\n"));
    }

    // Workflow integration tip
    console.log(chalk.blue("━━━ Workflow Integration ━━━\n"));
    console.log(chalk.white("Add to your local workflow:\n"));
    console.log(chalk.cyan("  # package.json"));
    console.log(chalk.cyan('  "scripts": {'));
    console.log(chalk.cyan(`    "prebuild": "npx reshot pull --format=${format}${output ? ` --output=${output}` : ''}"`));
    console.log(chalk.cyan('  }\n'));
    console.log(chalk.gray("  This ensures your build always uses the latest approved visuals."));
    console.log(chalk.gray("  If a visual is deleted, your build will fail (preventing broken images).\n"));

    return {
      success: true,
      assetCount,
      outputPath: path.resolve(outputPath),
      normalizedAssets,
      normalizationRepairs: normalization.repairs,
      meta,
    };

  } catch (error) {
    if (config.isAuthError(error)) {
      console.error(
        chalk.red("Error: Authentication failed. Run 'reshot auth' to re-authenticate.")
      );
    } else {
      console.error(chalk.red(`Error: ${error.message}`));
      if (process.env.RESHOT_DEBUG) {
        console.error(chalk.gray(error.stack));
      }
    }
    if (!noExit) {
      process.exit(1);
    }
    return { success: false, error: error.message };
  }
}

module.exports = pullCommand;
